# Generated by Django 4.1.3 on 2022-11-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades_alter_persona_options_persona_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'ordering': ['id'], 'verbose_name': 'Habilidades trabajor', 'verbose_name_plural': 'Habilidad Tecnica'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['id'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Datos de trabajador'},
        ),
    ]
