# Generated by Django 4.1.3 on 2022-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_persona_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='job',
            field=models.CharField(choices=[('0', 'SRE'), ('1', 'Economista'), ('2', 'Developer'), ('3', 'Test Automation')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
